apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-api
  template:
    metadata:
      labels:
        app: invoice-api
    spec:
      containers:
      - name: api-container
        image: invoice-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: invoice-api-service
spec:
  type: ClusterIP
  selector:
    app: invoice-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-ui
  template:
    metadata:
      labels:
        app: invoice-ui
    spec:
      containers:
      - name: ui-container
        image: invoice-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://invoice-api-service:8000"
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: invoice-ui-service
spec:
  type: LoadBalancer
  selector:
    app: invoice-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
